version: '3.2'

services:
  elasticsearch:
    build:
      context: "./elasticsearch/"
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./elasticsearch/config/elasticsearch.yml"
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - "./elasticsearch/data:/var/lib/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
    networks:
      - elk

  fluentd:
    build: ./fluentd
    volumes:
      - type: bind
        source: "./fluentd/conf/fluentd.conf"
        target: /usr/share/elasticsearch/config/fluentd.conf
        read_only: true
    networks:
      - elk
    ports:
      - "5170:5170"
      - "5170:5170/udp"
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: "./kibana/"
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./kibana/config/kibana.yml"
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
